  adjectives <-
  c("Anxious",
"Naughty",
"Stubborn",
"Sensitive",
"Intelligent",
"Nice",
"Emotional",
"Bad-tempered",
"Nervous",
"Mean",
"Distracted",
"Dishonest",
"Rude",
"Discreet",
"Crazy",
"Cheeky",
"Cheerful",
"Energetic",
"Untidy",
"Pessimistic",
"Optimistic",
"Unpleasant",
"Talkative",
"Calm",
"Passionate",
"Proud",
"Sincere",
"Lazy",
"Lively",
"Funny",
"Silly",
"Shy",
"Determined",
"Versatile",
"Sociable",
"Worried",
"Thoughtful",
"Humble",
"Friendly",
"Frank",
"Obedient",
"Honest",
"Fearless",
"Unfriendly",
"Generous",
"Compassionate",
"Warm-hearted",
"Disobedient",
"Straightforward",
"Selfish",
"Imaginative",
"Placid",
"Jealous",
"Helpful",
"Enthusiastic",
"Persistent",
"Sensible",
"Rational",
"Reserved",
"Self-confident",
"Bossy",
"Plucky",
"Patient",
"Impatient",
"Easygoing",
"Careless",
"Messy",
"Hard-working",
"Creative",
"Broad-minded",
"Faithful",
"Kind",
"Courageous",
"Loyal",
"Modest",
"Tidy",
"Confident",
"Attentive",
"Loving",
"Reliable",
"Scared",
"Conscientious",
"Good-tempered",
"Careful",
"Gentle",
"Neat",
"Dynamic",
"Fair-minded",
"Impartial",
"Supportive",
"Timid",
"Intellectual",
"Brave",
"Ambitious",
"Polite",
"Happy",
"Romantic",
"Diplomatic",
"Courteous",
"Humorous",
"Self-disciplined",
"Popular",
"Smart",
"Serious",
"Hypocritical",
"Adventurous")

persons <-
  c(
    "hill billy",
    "bretonion",
    "back water",
    "bumbkin",
    "yokel",
    "White bread",
    "Rye bread",
    "Hamburger",
    "Croissant",
    "Pretzel",
    "Bagel",
    "Donut",
    "saxonian",
    "welsh",
    "victorian",
    "from hell",
    "non sense",
    "you won't believe it"
  )

activities <-
  c(
    "Emoji Translation",
    "Friendship Tag",
    "Trivia",
    "Kiss, Marry, Kill",
    "Never Have I Ever",
    "skiing",
    "biking",
    "groceries",
    "baby sitting",
    "Name Game",
    "Binoculars",
    "Compass",
    "Hiking boots",
    "Flashlight",
    "Lighter",
    "Axe",
    "Knives",
    "Lantern",
    "Thermos bottle",
    "Barbeque grill",
    "First aid kit",
    "Campfire",
    "Backpack",
    "Tent",
    "Sleeping bag",
    "Camper van",
    "Cheese",
    "Egg",
    "Butter",
    "Margarine",
    "Yogurt",
    "Cottage cheese",
    "Ice cream",
    "Cream",
    "Sandwich",
    "Sausage",
    "Hamburger",
    "Hot dog",
    "Bread",
    "Pizza",
    "Steak",
    "Roast chicken",
    "Fish",
    "Seafood",
    "Ham",
    "Kebab",
    "Bacon",
    "Sour cream",
    "Boots",
    "Uggs",
    "Wellingtons",
    "Timberlands",
    "Lita",
    "Laced booties",
    "Steel-toe boots"
  )


#' Generate Random Message to Show of
#'
#' @param n How many messages to create
#'
#' @return string vector
#' @export
#'
#' @examples
#'
#' gnrndmsg()
#' gnrndmsg(1)
#' gnrndmsg(3)
#' gnrndmsg(n = 1)
#'
gnrndmsg <-
  function(n=1){
    if ( n == 1){
      paste(
        tolower(sample(adjectives, size = 1)),
        tolower(sample(persons, size = 1)),
        tolower(sample(activities, size = 1))
      )
    } else {
      vapply(
        X         = rep(1, n),
        FUN       = gnrndmsg,
        FUN.VALUE = ""
      )
    }
  }
